### ISSUE TITLE
`9.7.0` introduce a BREAKING CHANGE

### ISSUE THREAD

**Issue by arvinxx** [icons-pack/react-simple-icons#226]
Hi team. At first thanks for your good work to make us have a better DX for using `simple-icons` in React

But the latest 9.7.0 have a breaking change for the removal of all `windows` related icons (https://github.com/simple-icons/simple-icons/issues/11236), which makes our project failed:

```
Deprecation warnings:
 - The "function-whitespace-after" rule is deprecated.
 - The "media-feature-range-operator-space-after" rule is deprecated.
 - The "media-feature-range-operator-space-before" rule is deprecated.

$ tsc --noEmit
src/app/(main)/settings/sync/features/DeviceInfo/SystemIcon.tsx(7,3): error TS2305: Module '"@icons-pack/react-simple-icons"' has no exported member 'SiWindows11'.
Error: Process completed with exit code 2.
```

I think the reason the SiWindows11 missing is the upgrade of `simple-icons` from https://github.com/icons-pack/react-simple-icons/commit/bb8d92ae9eadeb28c3ed1e4b7b48e55e224d6807 this commit.

You can see the simple-icons 's release note here: 

https://github.com/simple-icons/simple-icons/releases/tag/13.0.0

there are 60+ icons that are removed, which why `simple-icons` just release the major version.

I suggest you to revert this commit to fix 9.7.0's breaking and then release a new major version (10.0.0) to match the simple-icons. Or there will be more projects using `@icons-pack/react-simple-icons` that will fail.

**Comment by wootsbot** [comment]
@arvinxx Thank you very much for the report
